### ISSUE TITLE
"No Permissions to write to /storage/emulated/0/Download/copy/2go.zip" even though I gave permission

### ISSUE THREAD

**Issue by nicolas-raoul** [k3b/ToGoZip#22]
Other settings are all default settings.

Maybe I have to create the `copy` folder by myself?
If so, the error message should be clearer.

Thanks! :-)

**Comment by k3b** [comment]
at startup the app check if it has permissions to write to the predefined output folder and if not it opens the folder chooser.

At least this is working on my android-7.1 devices.

I have added check that folder exists.

I added an additional test if proposed copy folder exists which will be available with next release

**Comment by k3b** [comment]
@nicolas-raoul  does the problem still existist in the current version or can i close this ticket

**Comment by k3b** [comment]
the app is using SAF (if you have android-5.0 and above) and it works without issues on my android-10 .

I have to further anayse and compare to material-files .....

**Comment by locuturus** [comment]
I wonder if this stack overflow might be [relevant](https://stackoverflow.com/questions/32563428/storage-access-framework-persist-permissions-not-working)

**Comment by k3b** [comment]
@locuturus  thanks for the stack-overflow.

I have added the missing flags from https://stackoverflow.com/questions/32563428/storage-access-framework-persist-permissions-not-working

In the zip is the pre-release of the apk with the new logo
https://github.com/k3b/ToGoZip/files/7462555/togozip-debug.zip

can you test if this fixes the problem.

I only have an android-10 device and the android-emulator does not work on my computer.

**Comment by locuturus** [comment]
DISPLAY_NAME column is null error in is preventing me from installing.

**Comment by k3b** [comment]
@locuturus : sorry something with the debug build went wrong.

this one should be working (at least i can install it on my android-10.

[togozip-debug2.zip](https://github.com/k3b/ToGoZip/files/7469087/togozip-debug2.zip)

**Comment by bege10** [comment]
This issue still exists with Fairphone 3, /e/OS (based on LineageOS for microG, Android 10)
